### ISSUE TITLE
Struct tuple experiment

### ISSUE THREAD

**Issue by ForNeVeR** [gsomix/skalarprodukt#24]
We need to check how homemade "struct tuples" could affect the performance of our type provider. Create new "tuple" type, replace `MakeTupleType` and `TupleGet` with their reimplementation for that type, and measure the resulting performance.

**Comment by gsomix** [comment]
Ok, I have some [results](https://github.com/gsomix/skalarprodukt/blob/60008ecd20a237001a49e9a4f0d1fce98d022c39/BenchmarkDotNet.Artifacts/results/GetSet-report-github.md). Let's discuss!
